### ISSUE TITLE
это для чего?

### ISSUE THREAD

**Issue by bziondik** [AnyaBoretskaya/port#1]
https://github.com/AnyaBoretskaya/port/blob/a36432f22e727b07e946472670b364f0a617c6b7/index.css#L9

**Comment by AnyaBoretskaya** [comment]
![image](https://user-images.githubusercontent.com/43179736/45841321-1bef3780-bd22-11e8-9cc4-9efbcbc53a16.png)
 Это тоже было в методе) С помощью margin мы можем задавать величину внешнего отступа, вроде как

**Comment by bziondik** [comment]
Оно к body в вашем коде не относится
body
{
    background-image: url("3.png");
    font-size: 26px;
    font-style: oblique;
    
   } 
{margin:25px;}

тогда надо написать
body {margin:25px;}

**Comment by AnyaBoretskaya** [comment]
исправила

**Comment by bziondik** [comment]
ok
