### ISSUE TITLE
что это за шрифт?

### ISSUE THREAD

**Issue by bziondik** [AnyaBoretskaya/port#2]
https://github.com/AnyaBoretskaya/port/blob/a36432f22e727b07e946472670b364f0a617c6b7/index.css#L35

**Comment by AnyaBoretskaya** [comment]
![1](https://user-images.githubusercontent.com/43179736/45840484-b1d59300-bd1f-11e8-9984-155e2cf9f846.png)
Я из методы нашла)

**Comment by bziondik** [comment]
У вас этот шрифт не подключен, попробуйте убрать, выглядит также

**Comment by AnyaBoretskaya** [comment]
Изменила на другой))

**Comment by bziondik** [comment]
ok
