### ISSUE TITLE
Задание 3 Ссылки не сделано

### ISSUE THREAD

**Issue by bziondik** [AnyaBoretskaya/port#6]
добавить 5 ссылок https://www.w3schools.com/html/html_links.asp
Сделать для каждой различное поведение по наведению/нажатию (меняет цвет, подчеркивание, открывается на этой странице, в новом окне...). Две ссылки в виде текста, три сделать в виде кнопки. Использовать классы для ссылок, псевдоклассы для поведения.
https://www.w3schools.com/css/css_link.asp

**Comment by AnyaBoretskaya** [comment]
![image](https://user-images.githubusercontent.com/43179736/45843978-b9019e80-bd29-11e8-8b21-5689a9d4219f.png)
Я делала ссылки в виде гифки или так нельзя?И в тексте были ссылки)

**Comment by AnyaBoretskaya** [comment]
![2](https://user-images.githubusercontent.com/43179736/45844209-6379c180-bd2a-11e8-9392-adb0de935b18.png)

**Comment by bziondik** [comment]
Сделайте хотя бы одну ссылку в виде кнопки

**Comment by AnyaBoretskaya** [comment]
Добавила)

**Comment by bziondik** [comment]
ok
